### ISSUE TITLE
Call to getArgument on NULL

### ISSUE THREAD

**Issue by srbarba** [dyorg/slim-token-authentication#3]
Hello,

When "Token is not found" I get:

`"Call to a member function getArgument() on null\nFile"`

Seeing your last commit:

```
-   'attribute' => $this->options['attribute']
+  'argument' => $this->options['argument']
```

The problem is in TokenSearch [52-58 lines]
I did a hotfix in my code:

```
- $argument = $route->getArgument($this->options['argument']);
+ $argument = is_null($route) ? $route->getArgument($this->options['argument']) : "";
```

**Comment by dyorg** [comment]
Hi @srbarba,

Thanks for report this issue. 

The $request->getAttribute('route') [53 line] should return a object $route, but sounds that sometimes it's returns null instead. To resolve this I added a conditional to check if $route is not null. Should works.

`
- $route = $request->getAttribute('route');
- $argument = $route->getArgument($this->options['argument']);
- if (!empty($argument)) {
-       return $argument;
+ if ($route = $request->getAttribute('route')) {
+       $argument = $route->getArgument($this->options['argument']);
+       if (!empty($argument)) {
+             return $argument;
+       }
`

For curiosity, what is your Slim version?

**Comment by srbarba** [comment]
Hi @dyorg,

I'm using Slim 3.5.0
