### ISSUE TITLE
Update composer package version

### ISSUE THREAD

**Issue by gtsop** [dyorg/slim-token-authentication#6]
Hello, is it possible to update the composer package to use the latest version (in master) by default?

I actually spend too much time trying to send a redirect in the error callback before i realized that the source code I was looking on github (master) was not the same one fetched by composer (0.3.2). The composer package properly shows the version number, I just didn't expect it to differ from master.

Thanks

**Comment by dyorg** [comment]
Hi @gtsop,

I just released 0.3.3 version, now composer will get the same code of current master.

Composer does not automatically get the master code, but the last release created on repo. So I forgot to make a new release to update with the custom error response fix. Sorry dude, it was my fault.
